### ISSUE TITLE
cmcnally Q4 Issues

### ISSUE THREAD

**Issue by cmcnally** [cmcnally/cmcnally#2]
```[tasklist]
### Tasks
- [ ] https://github.com/github/accessibility/issues/3461
- [ ] https://github.com/github/accessibility/issues/3462
- [ ] https://github.com/github/accessibility/issues/3463
- [ ] https://github.com/github/accessibility/issues/3464
- [ ] https://github.com/github/accessibility/issues/3465
- [ ] https://github.com/github/accessibility/issues/3315
- [ ] https://github.com/github/design-operations/issues/194
- [ ] https://github.com/github/social-media/issues/866
```
